stryker-mutator/mutation-testing-elements

- packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json
The `additionalProperties: false` might conflict with future additions to the schema and backwards compatibility. For example, a new property being added in 1.1, would not be a valid schema for 1.0.
Also added a regex to the schema version. Starts with 1, and then optionally a dot and any number.
> Remove `additionalProperties: false`, and add regex to schemaVersion

- .travis.yml
- README.md
- lerna.json
- package.json
> build(ci release): enable releasing via travis

- packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json
The position id does not work properly in the schema validator we use for Stryker4s (https://github.com/everit-org/json-schema)
> Remove position id

- .travis.yml
Adds a `node_modules` and maven repo cache
> build: add cache to speed up travis build

- packages/mutation-testing-elements/src/components/mutation-test-report-popup/mutation-test-report-popup.scss
Before:
After:
Popup arrow is now also the correct color for cautions (and any other extra colors we might add in the future).
> fix(popup): caution popup arrow color

- packages/mutation-testing-elements/src/components/mutation-test-report-file-legend.ts
Before:
After:
Legends are now center-aligned. Huge difference, I know. But it annoyed me.
> fix(legend): status alignments

- packages/mutation-testing-elements/src/components/mutation-test-report-breadcrumb.ts
- packages/mutation-testing-elements/src/components/mutation-test-report-totals.ts
- packages/mutation-testing-elements/src/lib/htmlHelpers.ts
- packages/mutation-testing-elements/test/unit/lib/htmlHelpers.spec.ts
- packages/mutation-testing-elements/testResources/scala-example/index.html
Make sure to support HTML documents that have set a `<base>` HTML tag. Use absolute urls constructed based on the current document, instead of the base.
Fixes #53
> fix(links): use absolute urls inside the report

- packages/mutation-testing-elements/webpack.common.js
- packages/mutation-testing-elements/webpack.dev.js
- packages/mutation-testing-elements/webpack.prod.js
Nothing earth-shattering. But using the Terser plugin shrinks the bundle from 378KB to 368KB. So why not use it?
> feat(build): use Terser plugin for smaller bundle

- packages/mutation-testing-metrics/src/calculateMetrics.ts
Lodash import was a non-existing dependency.
> fix(metrics): correct lodash import

- packages/mutation-testing-elements/package-lock.json
- packages/mutation-testing-elements/package.json
- packages/mutation-testing-metrics/package-lock.json
- packages/mutation-testing-metrics/package.json
- packages/mutation-testing-metrics/src/calculateMetrics.ts
- packages/mutation-testing-metrics/src/helpers.ts
Having a small helper function for groupBy instead of the `lodash.groupby` dependency shrinks the bundle from 234Kb to 222Kb
> build(optimize): remove lodash.groupby

- packages/mutation-testing-elements/postcss.config.js
> fix: font styling being excluded by postcss

- packages/mutation-testing-elements/webpack.common.js
Workaround is no longer necessary
> chore(build): use ts-loader project references

- packages/mutation-testing-elements/src/components/mutation-test-report-file/index.ts
- packages/mutation-testing-elements/test/integration/phpReport.it.spec.ts
- packages/mutation-testing-elements/test/integration/po/ElementSelector.po.ts
- packages/mutation-testing-elements/test/integration/po/ReportPage.ts
- packages/mutation-testing-elements/testResources/index.html
- packages/mutation-testing-elements/testResources/infection-php-example/index.html
- packages/mutation-testing-elements/testResources/infection-php-example/report.json
- workspace.code-workspace
Disable automatic loading of syntax highlight settings for unknown languages.
Include PHP in the supported languages.
Workaround for #393
> feat(elements): support syntax highlighting for php

- packages/mutation-testing-metrics-scala/build.sbt
- packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/DecoderTest.scala
- packages/mutation-testing-metrics-scala/npmProjPublish.sh
- packages/mutation-testing-metrics-scala/project/plugins.sbt
Publishes for mutation-testing-elements and mutation-testing-report-schema to Sonatype were broken since #356.
The reason for this is that sbt-sonatype prepares the files to be uploaded in a directory, and then batch uploads them to sonatype. When the base project is released, this works fine. However, the files will still be present after publishing. Then, when elements or report-schema is trying to be uploaded sbt-sonatype will also attempt to upload the files that are still there from the previous publish. Because releases on sonatype are immutable, this returns an error (`Repository ='releases:Releases' does not allow updating artifact='/io/stryker-mutator/mutation-testing-metrics-circe_2.12/1.3.1/mutation-testing-metrics-circe_2.12-1.3.1.pom'`).
This is similar to …
> fix(sonatype): fix release process for sonatype

- packages/mutation-testing-elements/package.json
- packages/mutation-testing-metrics-scala/build.sbt
- packages/mutation-testing-metrics-scala/project/build.properties
- packages/mutation-testing-metrics-scala/sonatype.sbt
- packages/mutation-testing-report-schema/package.json
Before:
```
❯ sbtn version          
> version
[info] schema / version
[info]  1.4.0
[info] elements / version
[info]  1.4.0
[info] metrics / version
[info]  1.4.0
[info] circe / version
[info]  1.4.0
```
After:
```
❯ sbtn version          
> version
[info] schema / version
[info]  1.4.1
[info] elements / version
[info]  1.4.1
[info] metrics / version
[info]  1.4.0
[info] circe / version
[info]  1.4.0
```
> fix(sonatype): give elements and report-schema their own sonatype version

- .gitignore
- packages/mutation-testing-metrics-scala/.vscode/settings.json
- packages/mutation-testing-metrics-scala/README.md
- packages/mutation-testing-metrics-scala/build.sbt
- packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportDecoder.scala
- packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportEncoder.scala
- packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/EncoderTest.scala
- packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/SchemaTest.scala
- packages/mutation-testing-metrics-scala/docs/README.md
- packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/Metrics.scala
- packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala
- packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/package.scala
- packages/mutation-testing-metrics-scala/metrics/src/test/scala/mutationtesting/MetricsTest.scala
- packages/mutation-testing-metrics-scala/metrics/src/test/scala/mutationtesting/MutationTestResultTest.scala
- packages/mutation-testing-metrics-scala/package.json
- packages/mutation-testing-metrics-scala/project/build.properties
- packages/mutation-testing-metrics-scala/project/plugins.sbt
Also add ScalaDoc comments from schema
BREAKING CHANGE: MutationTestReport was renamed to MutationTestResult
BREAKING CHANGE: MutationTestResult was renamed to FileResult
> feat(metrics-scala): align naming of types with schema

- packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json
Replaces `  `  with ` `. Or more specifically, replaces [non-breaking space](http://unicode.scarfboy.com/?s=%C2%A0) with a [normal space](http://unicode.scarfboy.com/?s=+).
I'm not sure how they ended up in the schema, but eslint let me know when I looked at the generated ts definitions
> fix(report-schema): replace no-break space with normal space

- packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/circe.scala
- packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala
- packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json
- packages/mutation-testing-report-schema/test/unit/TypeScript.spec.ts
- packages/mutation-testing-report-schema/testResources/strict-report.json
Add `statusReason` to a mutant result and `source` to a test file.
Status reason:
The reason that this mutant has this status. In the case of a killed mutant, this should be filled with the failure message(s) of the failing tests. In case of an error mutant, this should be filled with the error message.
Closes #891 
Source:
Full source code of the test file. This can be used to display in the report.
Closes #892
> feat(schema): add test file source and status reason

- lerna.json
- packages/mutation-testing-elements/test/unit/components/mutation-test-report-totals.spec.ts
- packages/mutation-testing-metrics/src/calculateMetrics.ts
- packages/mutation-testing-metrics/src/helpers/file.ts
- packages/mutation-testing-metrics/src/helpers/group-by.ts
- packages/mutation-testing-metrics/src/helpers/index.ts
- packages/mutation-testing-metrics/src/helpers/text.ts
- packages/mutation-testing-metrics/src/index.ts
- packages/mutation-testing-metrics/src/model/file-under-test-model.ts
- packages/mutation-testing-metrics/src/model/mutant-model.ts
- packages/mutation-testing-metrics/src/model/source-file.ts
- packages/mutation-testing-metrics/src/model/test-file-model.ts
- packages/mutation-testing-metrics/src/model/test-model.ts
- packages/mutation-testing-metrics/test/helpers/factories.ts
- packages/mutation-testing-metrics/test/unit/calculateMetrics.spec.ts
- packages/mutation-testing-metrics/test/unit/model/file-under-test-model.spec.ts
- packages/mutation-testing-metrics/test/unit/model/mutant-model.spec.ts
- packages/mutation-testing-metrics/test/unit/model/test-file-model.spec.ts
- packages/mutation-testing-metrics/test/unit/model/test-model.spec.ts
Enrich model with helper methods for reporters:
* `mutant.getOriginalLines()`
* `mutant.getMutatedLines()`
* `test.getLines()`
* `mutant.fileName`
* `mutant.sourceFile`
* `test.fileName`
* `test.sourceFile`
* `fileUnderTest.name`
* `testFile.name`
Also:
* Add mechanism to determine character range based on line/column position (heavily inspired by TypeScript source code)
* Add a reference to the source file in each mutant.
* Refactor: split helpers over multiple files.
> feat(file): add methods to retrieve source content

- packages/elements/src/components/app/app.component.ts
- packages/elements/src/lib/browser.ts
- packages/elements/test/unit/components/mutation-test-report-app.spec.ts
- packages/elements/test/unit/lib/browser.spec.ts
Fixes #1064
Checks if localStorage exists. If it exists but it is disabled, the browser will throw an error. So we can't just check if `localStorage !== undefined`
> fix(elements): add check if localStorage is available

- packages/elements/test/integration/drawer.it.spec.ts
- packages/elements/test/integration/lib/helpers.ts
- packages/elements/test/integration/test-view.it.spec.ts
Add a `waitUntil` function that waits until a certain given (async) condition is true, using intervals and timeouts. Based on `open-wc` (see link in comment), but with added support for Chai assertions.
My hope is this will also make the windows tests more stable
> test: add waitUntil helper function

- packages/elements/test/integration/drawer.it.spec.ts
Looking at all the open PR's with failing builds, it's always one of these two tests that fail. Since there is also a test for light mode, I think it's somewhat safe to disable these two to (hopefully) increase screenshot test stability.
> test: disable flaky screenshot tests

- packages/elements/src/components/app/app.component.ts
Lit was warning that performance is impacted by multiple render cycles. By setting all properties in earlier lifecycles, rendering is only done once.
> perf(mutation-test-report-app): only render once by setting props in earlier hooks

- packages/elements/src/components/drawer-mutant/drawer-mutant.component.ts
- packages/elements/test/unit/components/drawer-mutant.component.spec.ts
> fix(mutation-testing-elements): Don't render statusreason if it's an empty string

- packages/metrics/src/aggregate.ts
- packages/metrics/test/unit/aggregate.spec.ts
Make testIds and mutantIds unique accross all modules in `aggregateResultsByModule`
Fixes #1672
> fix(aggregate): also make ids unique

- packages/elements/src/components/file/file.scss
Fix #1937
Note that I did not manage to test the change as I could not figure out how to and there are no docs describing how to contribute.
> fix: Set theme color for ignored status mutants

- packages/elements/test/unit/components/app.component.spec.ts
- packages/elements/testResources/csharp-example/mutation-report.json
- packages/metrics/src/calculateMetrics.ts
> fix: don't create test metrics if test files is empty

- docs/supported-mutators.md
Hello guys! 
It seems like the "Back to Top" buttons are broken on the "Supported mutators" page. If you try to click it, nothing happens. So, I fixed the links on these buttons and replaced the relative path `#supported-mutators` with just `#`. This resolved the issue for me. 
Hope this PR help, guys!
> Fix broken "Back to Top" buttons

- packages/elements/src/components/file/file.component.ts
- packages/elements/src/components/file/file.scss
- packages/elements/src/components/mutant-view/mutant-view.ts
- packages/elements/src/lib/html-helpers.ts
- packages/elements/test/helpers/factory.ts
- packages/elements/test/unit/components/mutant-view.component.spec.ts
- packages/elements/test/unit/components/state-filter.component.spec.ts
- packages/elements/testResources/csharp-example/mutation-report.json
- packages/metrics-scala/circe/src/main/scala/mutationtesting/circe.scala
- packages/metrics-scala/metrics/src/main/scala/mutationtesting/MetricsResult.scala
- packages/metrics-scala/metrics/src/main/scala/mutationtesting/MutantStatus.scala
- packages/metrics-scala/metrics/src/test/scala/mutationtesting/MetricsResultTest.scala
- packages/metrics/src/calculateMetrics.ts
- packages/metrics/src/model/metrics.ts
- packages/metrics/test/unit/calculateMetrics.spec.ts
- packages/report-schema/src/mutation-testing-report-schema.json
Do tell if more needs to be changed or tested.
closes #2424
BREAKING CHANGE: `Pending` is now also a valid mutant status
> feat(schema): add `Pending` status to JSON schema

- packages/elements/src/components/metrics-table/metrics-table.component.ts
Looks nice with the real-time updates 😃
> fix(elements-table): transition score colors

- packages/elements/src/components/drawer/drawer.component.ts
- packages/elements/test/unit/components/drawer.component.spec.ts
> fix(elements): close drawer when pressing Escape

- .github/setup/action.yml
- .github/workflows/ci.yml
- .github/workflows/mutation-testing.yml
- .github/workflows/release.yml
- .github/workflows/update-screenshots.yml
- nx.json
Nx has recently introduced a new free plan that is about 1/3rd of the monthly credits. All it does is save the .nx/ cache folder, so we might as well just cache it on GitHub's cache and not be dependent on a third-party service.
Also sets up a composite action to set up the CI env
> chore: disconnect from nx cloud

- .github/setup/action.yml
Since the ubuntu-24 image, sbt is no longer included by default, so we have to install it
> chore: add setup-sbt to GH actions

- docs/supported-mutators.md
Add new unsigned right sift and Append/Prepend mutations for Stryker.NET.
See https://github.com/stryker-mutator/stryker-net/pull/3200 and https://github.com/stryker-mutator/stryker-net/pull/3199.
> docs: Add new Stryker.NET mutations
