mutation-testing-report-schema.json

I've updated the schema to the new flat structure. And also added some assertions to the schema:
- Thresholds must be between 0 and 100
- Line numbers are positive
- `mutants` array elements are unique
- Report does not contain elements that are not defined in the schema (`additionalProperties: false`)
Fixes #1

Update schema to flat structure

---

packages/mutation-testing-elements/src/components/mutation-test-report-file/mutation-test-report-file.scss

feat(popup): make popup visible at bottom of the screen

---

packages/mutation-testing-elements/src/components/mutation-test-report-popup/mutation-test-report-popup.scss
packages/mutation-testing-elements/src/components/mutation-test-report-popup/mutation-test-report-popup.ts

fix(popup): Popup offset

---

packages/mutation-testing-elements/src/lib/router.ts
packages/mutation-testing-elements/test/unit/lib/router.spec.ts

fix(router): allow url encoded chars in file names

---

packages/mutation-testing-elements/src/components/mutation-test-report-file-legend/index.scss

feat(elements): allow override of top offset

---

README.md
packages/mutation-testing-elements/README.md
packages/mutation-testing-metrics-scala/README.md
packages/mutation-testing-metrics/README.md
packages/mutation-testing-report-schema/README.md

We all love badges! Updated the URL to the CI badge as well as added some more mutation score badges

docs(🥇 ) add badges

---

packages/mutation-testing-metrics-scala/.npmignore
packages/mutation-testing-metrics/.npmignore
packages/mutation-testing-report-schema/.npmignore

chore(build): update npmignores

---

.github/workflows/mutation-testing.yml
package-lock.json
packages/mutation-testing-elements/test/unit/components/mutation-test-report-app.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-breadcrumb.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-file-legend.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-file.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-modal-dialog.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-mutant.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-popup.spec.ts
packages/mutation-testing-elements/test/unit/components/mutation-test-report-totals.spec.ts
packages/mutation-testing-elements/test/unit/helpers/CustomElementFixture.ts

Make sure the @stryker-mutator/api package is hoisted to toplevel.
Workaround for: https://github.com/stryker-mutator/stryker/issues/2025

test(mutation): align on stryker version

---

package-lock.json
package.json

build(deps-dev): remove @stryker-mutator/html-reporter

---

package-lock.json
package.json

Update to github-actions compatible version (ideally we'd fetch a version independent of github actions environment...)

build(deps-dev): bump chromedriver from 79.0.3 to 81.0.0

---

packages/mutation-testing-elements/test/unit/components/mutation-test-report-app.spec.ts
packages/mutation-testing-elements/testResources/csharp-example/mutation-report.json
packages/mutation-testing-elements/testResources/deep-dir-example/mutation-report.json
packages/mutation-testing-elements/testResources/infection-php-example/report.json
packages/mutation-testing-elements/testResources/install-local-example/index.html
packages/mutation-testing-elements/testResources/pitest-example/report.js
packages/mutation-testing-elements/testResources/scala-example/index.html
packages/mutation-testing-elements/testResources/scala-example/mutation-report.json
packages/mutation-testing-elements/testResources/simple-example/mutation-report.json
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportDecoder.scala
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportEncoder.scala
packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/EncoderTest.scala
packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/SchemaTest.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala
packages/mutation-testing-report-schema/src/api/MutationTestResult.ts
packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json

Add absolute path as metadata as described in issue #588 (and in the context of the ongoing PR on stryker-net https://github.com/stryker-mutator/stryker-net/pull/1267).

Add absolute path as metadata

---

packages/mutation-testing-metrics-scala/.scalafix.conf
packages/mutation-testing-metrics-scala/.scalafmt.conf
packages/mutation-testing-metrics-scala/README.md
packages/mutation-testing-metrics-scala/build.sbt
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/CodecOps.scala
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportCodec.scala
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportDecoder.scala
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/MutationReportEncoder.scala
packages/mutation-testing-metrics-scala/circe/src/main/scala/mutationtesting/circe.scala
packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/EncoderTest.scala
packages/mutation-testing-metrics-scala/circe/src/test/scala/mutationtesting/SchemaTest.scala
packages/mutation-testing-metrics-scala/docs/README.md
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/Metrics.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/MetricsResult.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/MutantStatus.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/Thresholds.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/mutationTestResult.scala
packages/mutation-testing-metrics-scala/metrics/src/main/scala/mutationtesting/package.scala
packages/mutation-testing-metrics-scala/metrics/src/test/scala/mutationtesting/MetricsResultTest.scala
packages/mutation-testing-metrics-scala/metrics/src/test/scala/mutationtesting/MutationTestResultTest.scala

Also add a lot of improved tests

feat(metrics-scala): add support for test coverage and metadata

---

docs/mutant-states-and-metrics.md

Documents what has been decided in #872

docs(states and metrics): document test metrics

---

.github/workflows/ci.yml
.github/workflows/mutation-testing.yml
packages/mutation-testing-elements/karma.conf.js
packages/mutation-testing-elements/package.json
packages/mutation-testing-elements/test/unit/index.js

chore(elements): enable karma tests again

---

packages/elements/test/integration/test-view.it.spec.ts

test(windows): fix flaky Windows tests in CI

---

packages/report-schema/package.json

Node needs to defined a main in the exports, too.

fix: package.json from package report-schema

---

packages/report-schema/package.json
packages/report-schema/test/unit/exports.spec.ts
workspace.code-workspace

- fix(exports): add default export for the schema
- test(exports): verify correct exports in unit test

fix(exports): add default export for the schema

---

docs/supported-mutators.md

Add recent mutators:
* Optional chaining 
* Object literal
* Regex

docs(mutators): add recent mutators

---

docs/supported-mutators.md

The long awaited mutator has arrived. BLOCK MUTATIONS!!

chore: Update supported mutators for Stryker.NET

---

package.json

build: set test concurrency to 1

---

docs/static-mutants.md

Solving the race condition on the remarks of #1547 
@hugo-vrijswijk

docs(static-mutants): slightly better wording

---

packages/elements/src/components/app/app.component.ts
packages/elements/src/components/app/app.scss
packages/elements/src/components/metrics-table/metrics-table.component.ts
packages/elements/src/components/mutant-view/mutant-view.ts
packages/elements/src/components/test-view/test-view.ts
packages/elements/test/integration/po/ResultTableRow.po.ts
packages/elements/test/unit/components/mutant-view.component.spec.ts
packages/elements/test/unit/components/test-view.component.spec.ts
packages/elements/test/unit/components/totals.component.spec.ts

Adding some aria descriptors, and making tabbing through the tabs a bit clearer (outline was not visible before)

feat: improve accessibility of app and metrics-table components

---

docs/mutant-states-and-metrics.md

docs(states and metrics): add `Pending` to possible mutant states

---

package.json
packages/elements/package.json
packages/metrics-scala/package.json
packages/metrics/package.json
packages/report-schema/package.json

chore: add directory property in `packages.json`

---

docs/implementing-real-time-reporting.md

docs(real-time): add information about implementing real-time reporting

---

packages/metrics-scala/build.sbt

Reverts stryker-mutator/mutation-testing-elements#3029

Revert "build(deps-dev): update scala-library from 2.12.18 to 2.13.12"

---

packages/elements/src/components/drawer-mutant/drawer-mutant.component.ts
packages/elements/src/components/drawer-test/drawer-test.component.ts
packages/elements/src/components/drawer/drawer.component.ts
packages/metrics-scala/project/plugins.sbt

https://github.com/user-attachments/assets/1920412a-503f-4d4a-be20-2bc08abc9176

fix(elements): make drawer header sticky

---

packages/elements/src/components/drawer-mutant/drawer-mutant.component.ts
packages/elements/test/unit/components/drawer-mutant.component.spec.ts

fix(elements): consider statusReason for drawer detail

---

packages/elements/src/components/drawer/drawer.component.ts
packages/elements/src/components/file/file.component.ts
packages/elements/src/components/file/file.scss
packages/elements/src/components/file/util.ts
packages/elements/src/components/test-file/test-file.component.ts
packages/elements/src/components/test-file/test-file.scss
packages/elements/tailwind.config.ts

A bit of a hassle, but it looks quite nice. Also fixes an issue with tests staying selected when clicking around in the test view
https://github.com/user-attachments/assets/94653870-3229-480f-91c4-235980eb0654

feat(elements): animate dot/triangle opening/closing

---

packages/elements/src/components/app/app.component.ts
packages/elements/src/components/drawer/drawer.component.ts
packages/elements/src/components/file/file.component.ts

https://github.com/user-attachments/assets/81848d31-abe0-475b-852c-fc540de4d255

feat(elements): listen to prefers-color-scheme event to switch theme

---

.github/renovate.json
.github/setup/action.yml
.github/workflows/ci.yml
.github/workflows/mutation-testing.yml
.github/workflows/release.yml
.github/workflows/update-screenshots.yml
package-lock.json
package.json

The `NX_REJECT_UNKNOWN_LOCAL_CACHE` environment variable is deprecated and won't work for much longer, unfortunately. Nx powerpack has a similar feature.

chore: setup powerpack fs-shared-cache

---

package-lock.json
packages/real-time/package.json

chore: remove @types/eventsource

---

package-lock.json
packages/elements/eslint.config.ts
packages/eslint-config-mte/README.md
packages/eslint-config-mte/eslint.config.ts
packages/eslint-config-mte/index.ts
packages/eslint-config-mte/package.json
packages/eslint-plugin-mte/eslint.config.js
packages/eslint-plugin-mte/index.d.ts
packages/metrics/eslint.config.js
packages/metrics/eslint.config.ts
packages/real-time/eslint.config.js
packages/real-time/eslint.config.ts
packages/report-schema/eslint.config.js
packages/report-schema/eslint.config.ts
tsconfig.node.json
workspace.code-workspace

And use TS eslint config files

chore: rename eslint-plugin-mte to eslint-config-mte
